export const TUNNEL_ID = 'some-tunnel-id'
export const REQUEST_ID = 'some-request-id'
export const REQUEST_BODY = 'Hello'
export const RESPONSE_BODY = 'World'
export const TUNNEL_ID_HEADER = 'x-tunnel-id'
