export const defaultResponseStatus = 200

export const tsFileHeader = '// This file was generated by the Opapi Generator\n/* eslint-disable */\n// @ts-nocheck'

export const invalidLine = "import { URL, URLSearchParams } from 'url';"
