// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Acl extends pulumi.CustomResource {
    /**
     * Get an existing Acl resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AclState, opts?: pulumi.CustomResourceOptions): Acl {
        return new Acl(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'redpanda:index/acl:Acl';

    /**
     * Returns true if the given object is an instance of Acl.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Acl {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Acl.__pulumiType;
    }

    /**
     * When set to true, allows the resource to be removed from state even if the cluster is unreachable
     */
    declare public readonly allowDeletion: pulumi.Output<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
     */
    declare public readonly clusterApiUrl: pulumi.Output<string>;
    /**
     * The host address to use for this ACL
     */
    declare public readonly host: pulumi.Output<string>;
    /**
     * The operation type that shall be allowed or denied (e.g READ)
     */
    declare public readonly operation: pulumi.Output<string>;
    /**
     * The permission type. It determines whether the operation should be ALLOWED or DENIED
     */
    declare public readonly permissionType: pulumi.Output<string>;
    /**
     * The principal to apply this ACL for
     */
    declare public readonly principal: pulumi.Output<string>;
    /**
     * The name of the resource this ACL entry will be on
     */
    declare public readonly resourceName: pulumi.Output<string>;
    /**
     * The pattern type of the resource. It determines the strategy how the provided resource name is matched (LITERAL, MATCH, PREFIXED, etc ...) against the actual resource names
     */
    declare public readonly resourcePatternType: pulumi.Output<string>;
    /**
     * The type of the resource (TOPIC, GROUP, etc...) this ACL shall target
     */
    declare public readonly resourceType: pulumi.Output<string>;

    /**
     * Create a Acl resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AclArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AclArgs | AclState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AclState | undefined;
            resourceInputs["allowDeletion"] = state?.allowDeletion;
            resourceInputs["clusterApiUrl"] = state?.clusterApiUrl;
            resourceInputs["host"] = state?.host;
            resourceInputs["operation"] = state?.operation;
            resourceInputs["permissionType"] = state?.permissionType;
            resourceInputs["principal"] = state?.principal;
            resourceInputs["resourceName"] = state?.resourceName;
            resourceInputs["resourcePatternType"] = state?.resourcePatternType;
            resourceInputs["resourceType"] = state?.resourceType;
        } else {
            const args = argsOrState as AclArgs | undefined;
            if (args?.clusterApiUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterApiUrl'");
            }
            if (args?.host === undefined && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            if (args?.operation === undefined && !opts.urn) {
                throw new Error("Missing required property 'operation'");
            }
            if (args?.permissionType === undefined && !opts.urn) {
                throw new Error("Missing required property 'permissionType'");
            }
            if (args?.principal === undefined && !opts.urn) {
                throw new Error("Missing required property 'principal'");
            }
            if (args?.resourceName === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceName'");
            }
            if (args?.resourcePatternType === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourcePatternType'");
            }
            if (args?.resourceType === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceType'");
            }
            resourceInputs["allowDeletion"] = args?.allowDeletion;
            resourceInputs["clusterApiUrl"] = args?.clusterApiUrl;
            resourceInputs["host"] = args?.host;
            resourceInputs["operation"] = args?.operation;
            resourceInputs["permissionType"] = args?.permissionType;
            resourceInputs["principal"] = args?.principal;
            resourceInputs["resourceName"] = args?.resourceName;
            resourceInputs["resourcePatternType"] = args?.resourcePatternType;
            resourceInputs["resourceType"] = args?.resourceType;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Acl.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Acl resources.
 */
export interface AclState {
    /**
     * When set to true, allows the resource to be removed from state even if the cluster is unreachable
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
     */
    clusterApiUrl?: pulumi.Input<string>;
    /**
     * The host address to use for this ACL
     */
    host?: pulumi.Input<string>;
    /**
     * The operation type that shall be allowed or denied (e.g READ)
     */
    operation?: pulumi.Input<string>;
    /**
     * The permission type. It determines whether the operation should be ALLOWED or DENIED
     */
    permissionType?: pulumi.Input<string>;
    /**
     * The principal to apply this ACL for
     */
    principal?: pulumi.Input<string>;
    /**
     * The name of the resource this ACL entry will be on
     */
    resourceName?: pulumi.Input<string>;
    /**
     * The pattern type of the resource. It determines the strategy how the provided resource name is matched (LITERAL, MATCH, PREFIXED, etc ...) against the actual resource names
     */
    resourcePatternType?: pulumi.Input<string>;
    /**
     * The type of the resource (TOPIC, GROUP, etc...) this ACL shall target
     */
    resourceType?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Acl resource.
 */
export interface AclArgs {
    /**
     * When set to true, allows the resource to be removed from state even if the cluster is unreachable
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
     */
    clusterApiUrl: pulumi.Input<string>;
    /**
     * The host address to use for this ACL
     */
    host: pulumi.Input<string>;
    /**
     * The operation type that shall be allowed or denied (e.g READ)
     */
    operation: pulumi.Input<string>;
    /**
     * The permission type. It determines whether the operation should be ALLOWED or DENIED
     */
    permissionType: pulumi.Input<string>;
    /**
     * The principal to apply this ACL for
     */
    principal: pulumi.Input<string>;
    /**
     * The name of the resource this ACL entry will be on
     */
    resourceName: pulumi.Input<string>;
    /**
     * The pattern type of the resource. It determines the strategy how the provided resource name is matched (LITERAL, MATCH, PREFIXED, etc ...) against the actual resource names
     */
    resourcePatternType: pulumi.Input<string>;
    /**
     * The type of the resource (TOPIC, GROUP, etc...) this ACL shall target
     */
    resourceType: pulumi.Input<string>;
}
