// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSchema(args: GetSchemaArgs, opts?: pulumi.InvokeOptions): Promise<GetSchemaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("redpanda:index/getSchema:getSchema", {
        "clusterId": args.clusterId,
        "subject": args.subject,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSchema.
 */
export interface GetSchemaArgs {
    clusterId: string;
    subject: string;
    version?: number;
}

/**
 * A collection of values returned by getSchema.
 */
export interface GetSchemaResult {
    readonly clusterId: string;
    readonly id: number;
    readonly references: outputs.GetSchemaReference[];
    readonly schema: string;
    readonly schemaType: string;
    readonly subject: string;
    readonly version: number;
}
export function getSchemaOutput(args: GetSchemaOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSchemaResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("redpanda:index/getSchema:getSchema", {
        "clusterId": args.clusterId,
        "subject": args.subject,
        "version": args.version,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSchema.
 */
export interface GetSchemaOutputArgs {
    clusterId: pulumi.Input<string>;
    subject: pulumi.Input<string>;
    version?: pulumi.Input<number>;
}
