// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getServerlessCluster(args: GetServerlessClusterArgs, opts?: pulumi.InvokeOptions): Promise<GetServerlessClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("redpanda:index/getServerlessCluster:getServerlessCluster", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerlessCluster.
 */
export interface GetServerlessClusterArgs {
    id: string;
}

/**
 * A collection of values returned by getServerlessCluster.
 */
export interface GetServerlessClusterResult {
    readonly clusterApiUrl: string;
    readonly id: string;
    readonly name: string;
    readonly resourceGroupId: string;
    readonly serverlessRegion: string;
}
export function getServerlessClusterOutput(args: GetServerlessClusterOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerlessClusterResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("redpanda:index/getServerlessCluster:getServerlessCluster", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getServerlessCluster.
 */
export interface GetServerlessClusterOutputArgs {
    id: pulumi.Input<string>;
}
