// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getThroughputTiers(args?: GetThroughputTiersArgs, opts?: pulumi.InvokeOptions): Promise<GetThroughputTiersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("redpanda:index/getThroughputTiers:getThroughputTiers", {
        "cloudProvider": args.cloudProvider,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getThroughputTiers.
 */
export interface GetThroughputTiersArgs {
    cloudProvider?: string;
}

/**
 * A collection of values returned by getThroughputTiers.
 */
export interface GetThroughputTiersResult {
    readonly cloudProvider?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly throughputTiers: outputs.GetThroughputTiersThroughputTier[];
}
export function getThroughputTiersOutput(args?: GetThroughputTiersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetThroughputTiersResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("redpanda:index/getThroughputTiers:getThroughputTiers", {
        "cloudProvider": args.cloudProvider,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getThroughputTiers.
 */
export interface GetThroughputTiersOutputArgs {
    cloudProvider?: pulumi.Input<string>;
}
