// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Network extends pulumi.CustomResource {
    /**
     * Get an existing Network resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkState, opts?: pulumi.CustomResourceOptions): Network {
        return new Network(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'redpanda:index/network:Network';

    /**
     * Returns true if the given object is an instance of Network.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Network {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Network.__pulumiType;
    }

    /**
     * The<span pulumi-lang-nodejs=" cidrBlock " pulumi-lang-dotnet=" CidrBlock " pulumi-lang-go=" cidrBlock " pulumi-lang-python=" cidr_block " pulumi-lang-yaml=" cidrBlock " pulumi-lang-java=" cidrBlock "> cidr_block </span>to create the network in
     */
    declare public readonly cidrBlock: pulumi.Output<string | undefined>;
    /**
     * The cloud provider to create the network in.
     */
    declare public readonly cloudProvider: pulumi.Output<string>;
    /**
     * The type of cluster this network is associated with, can be one of dedicated or byoc
     */
    declare public readonly clusterType: pulumi.Output<string>;
    declare public readonly customerManagedResources: pulumi.Output<outputs.NetworkCustomerManagedResources | undefined>;
    /**
     * Name of the network
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The region to create the network in.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The ID of the resource group in which to create the network
     */
    declare public readonly resourceGroupId: pulumi.Output<string>;
    /**
     * Current state of the network.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.NetworkTimeouts | undefined>;
    /**
     * Network availability zones.
     */
    declare public /*out*/ readonly zones: pulumi.Output<string[]>;

    /**
     * Create a Network resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkArgs | NetworkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkState | undefined;
            resourceInputs["cidrBlock"] = state?.cidrBlock;
            resourceInputs["cloudProvider"] = state?.cloudProvider;
            resourceInputs["clusterType"] = state?.clusterType;
            resourceInputs["customerManagedResources"] = state?.customerManagedResources;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
            resourceInputs["resourceGroupId"] = state?.resourceGroupId;
            resourceInputs["state"] = state?.state;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["zones"] = state?.zones;
        } else {
            const args = argsOrState as NetworkArgs | undefined;
            if (args?.cloudProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudProvider'");
            }
            if (args?.clusterType === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterType'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.resourceGroupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceGroupId'");
            }
            resourceInputs["cidrBlock"] = args?.cidrBlock;
            resourceInputs["cloudProvider"] = args?.cloudProvider;
            resourceInputs["clusterType"] = args?.clusterType;
            resourceInputs["customerManagedResources"] = args?.customerManagedResources;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["resourceGroupId"] = args?.resourceGroupId;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["zones"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Network.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Network resources.
 */
export interface NetworkState {
    /**
     * The<span pulumi-lang-nodejs=" cidrBlock " pulumi-lang-dotnet=" CidrBlock " pulumi-lang-go=" cidrBlock " pulumi-lang-python=" cidr_block " pulumi-lang-yaml=" cidrBlock " pulumi-lang-java=" cidrBlock "> cidr_block </span>to create the network in
     */
    cidrBlock?: pulumi.Input<string>;
    /**
     * The cloud provider to create the network in.
     */
    cloudProvider?: pulumi.Input<string>;
    /**
     * The type of cluster this network is associated with, can be one of dedicated or byoc
     */
    clusterType?: pulumi.Input<string>;
    customerManagedResources?: pulumi.Input<inputs.NetworkCustomerManagedResources>;
    /**
     * Name of the network
     */
    name?: pulumi.Input<string>;
    /**
     * The region to create the network in.
     */
    region?: pulumi.Input<string>;
    /**
     * The ID of the resource group in which to create the network
     */
    resourceGroupId?: pulumi.Input<string>;
    /**
     * Current state of the network.
     */
    state?: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.NetworkTimeouts>;
    /**
     * Network availability zones.
     */
    zones?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Network resource.
 */
export interface NetworkArgs {
    /**
     * The<span pulumi-lang-nodejs=" cidrBlock " pulumi-lang-dotnet=" CidrBlock " pulumi-lang-go=" cidrBlock " pulumi-lang-python=" cidr_block " pulumi-lang-yaml=" cidrBlock " pulumi-lang-java=" cidrBlock "> cidr_block </span>to create the network in
     */
    cidrBlock?: pulumi.Input<string>;
    /**
     * The cloud provider to create the network in.
     */
    cloudProvider: pulumi.Input<string>;
    /**
     * The type of cluster this network is associated with, can be one of dedicated or byoc
     */
    clusterType: pulumi.Input<string>;
    customerManagedResources?: pulumi.Input<inputs.NetworkCustomerManagedResources>;
    /**
     * Name of the network
     */
    name?: pulumi.Input<string>;
    /**
     * The region to create the network in.
     */
    region: pulumi.Input<string>;
    /**
     * The ID of the resource group in which to create the network
     */
    resourceGroupId: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.NetworkTimeouts>;
}
