// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Pipeline extends pulumi.CustomResource {
    /**
     * Get an existing Pipeline resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PipelineState, opts?: pulumi.CustomResourceOptions): Pipeline {
        return new Pipeline(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'redpanda:index/pipeline:Pipeline';

    /**
     * Returns true if the given object is an instance of Pipeline.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Pipeline {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Pipeline.__pulumiType;
    }

    /**
     * Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
     */
    declare public readonly allowDeletion: pulumi.Output<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
     */
    declare public readonly clusterApiUrl: pulumi.Output<string>;
    /**
     * The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
     */
    declare public readonly configYaml: pulumi.Output<string>;
    /**
     * Optional description of the pipeline.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * User-friendly display name for the pipeline.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * Resource allocation for the pipeline.
     */
    declare public readonly resources: pulumi.Output<outputs.PipelineResources>;
    /**
     * Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
     */
    declare public readonly serviceAccount: pulumi.Output<outputs.PipelineServiceAccount | undefined>;
    /**
     * Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
     */
    declare public readonly state: pulumi.Output<string>;
    /**
     * Pipeline status information.
     */
    declare public /*out*/ readonly status: pulumi.Output<outputs.PipelineStatus>;
    /**
     * Key-value pairs to tag the pipeline for organization and filtering.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.PipelineTimeouts | undefined>;
    /**
     * URL to connect to the pipeline's HTTP server, if applicable.
     */
    declare public /*out*/ readonly url: pulumi.Output<string>;

    /**
     * Create a Pipeline resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PipelineArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PipelineArgs | PipelineState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PipelineState | undefined;
            resourceInputs["allowDeletion"] = state?.allowDeletion;
            resourceInputs["clusterApiUrl"] = state?.clusterApiUrl;
            resourceInputs["configYaml"] = state?.configYaml;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["resources"] = state?.resources;
            resourceInputs["serviceAccount"] = state?.serviceAccount;
            resourceInputs["state"] = state?.state;
            resourceInputs["status"] = state?.status;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["url"] = state?.url;
        } else {
            const args = argsOrState as PipelineArgs | undefined;
            if (args?.clusterApiUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterApiUrl'");
            }
            if (args?.configYaml === undefined && !opts.urn) {
                throw new Error("Missing required property 'configYaml'");
            }
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            resourceInputs["allowDeletion"] = args?.allowDeletion;
            resourceInputs["clusterApiUrl"] = args?.clusterApiUrl;
            resourceInputs["configYaml"] = args?.configYaml ? pulumi.secret(args.configYaml) : undefined;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["resources"] = args?.resources;
            resourceInputs["serviceAccount"] = args?.serviceAccount;
            resourceInputs["state"] = args?.state;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["url"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["configYaml"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Pipeline.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Pipeline resources.
 */
export interface PipelineState {
    /**
     * Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
     */
    clusterApiUrl?: pulumi.Input<string>;
    /**
     * The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
     */
    configYaml?: pulumi.Input<string>;
    /**
     * Optional description of the pipeline.
     */
    description?: pulumi.Input<string>;
    /**
     * User-friendly display name for the pipeline.
     */
    displayName?: pulumi.Input<string>;
    /**
     * Resource allocation for the pipeline.
     */
    resources?: pulumi.Input<inputs.PipelineResources>;
    /**
     * Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
     */
    serviceAccount?: pulumi.Input<inputs.PipelineServiceAccount>;
    /**
     * Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
     */
    state?: pulumi.Input<string>;
    /**
     * Pipeline status information.
     */
    status?: pulumi.Input<inputs.PipelineStatus>;
    /**
     * Key-value pairs to tag the pipeline for organization and filtering.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.PipelineTimeouts>;
    /**
     * URL to connect to the pipeline's HTTP server, if applicable.
     */
    url?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Pipeline resource.
 */
export interface PipelineArgs {
    /**
     * Allows deletion of the pipeline. Default is false. Must be set to true to delete the resource.
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports.
     */
    clusterApiUrl: pulumi.Input<string>;
    /**
     * The Redpanda Connect pipeline configuration in YAML format. See https://docs.redpanda.com/redpanda-cloud/develop/connect/configuration/about for configuration details.
     */
    configYaml: pulumi.Input<string>;
    /**
     * Optional description of the pipeline.
     */
    description?: pulumi.Input<string>;
    /**
     * User-friendly display name for the pipeline.
     */
    displayName: pulumi.Input<string>;
    /**
     * Resource allocation for the pipeline.
     */
    resources?: pulumi.Input<inputs.PipelineResources>;
    /**
     * Service account credentials for the pipeline. Used to authenticate the pipeline with external services.
     */
    serviceAccount?: pulumi.Input<inputs.PipelineServiceAccount>;
    /**
     * Desired state of the pipeline: 'running' or 'stopped'. The provider will ensure the pipeline reaches this state after create/update operations.
     */
    state?: pulumi.Input<string>;
    /**
     * Key-value pairs to tag the pipeline for organization and filtering.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.PipelineTimeouts>;
}
