// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RoleAssignment extends pulumi.CustomResource {
    /**
     * Get an existing RoleAssignment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RoleAssignmentState, opts?: pulumi.CustomResourceOptions): RoleAssignment {
        return new RoleAssignment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'redpanda:index/roleAssignment:RoleAssignment';

    /**
     * Returns true if the given object is an instance of RoleAssignment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RoleAssignment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RoleAssignment.__pulumiType;
    }

    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
     */
    declare public readonly clusterApiUrl: pulumi.Output<string>;
    /**
     * The principal to assign the role to. Specify just the username (e.g., `"john.doe"`)
     */
    declare public readonly principal: pulumi.Output<string>;
    /**
     * The name of the role to assign
     */
    declare public readonly roleName: pulumi.Output<string>;

    /**
     * Create a RoleAssignment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RoleAssignmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RoleAssignmentArgs | RoleAssignmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RoleAssignmentState | undefined;
            resourceInputs["clusterApiUrl"] = state?.clusterApiUrl;
            resourceInputs["principal"] = state?.principal;
            resourceInputs["roleName"] = state?.roleName;
        } else {
            const args = argsOrState as RoleAssignmentArgs | undefined;
            if (args?.clusterApiUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterApiUrl'");
            }
            if (args?.principal === undefined && !opts.urn) {
                throw new Error("Missing required property 'principal'");
            }
            if (args?.roleName === undefined && !opts.urn) {
                throw new Error("Missing required property 'roleName'");
            }
            resourceInputs["clusterApiUrl"] = args?.clusterApiUrl;
            resourceInputs["principal"] = args?.principal;
            resourceInputs["roleName"] = args?.roleName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RoleAssignment.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering RoleAssignment resources.
 */
export interface RoleAssignmentState {
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
     */
    clusterApiUrl?: pulumi.Input<string>;
    /**
     * The principal to assign the role to. Specify just the username (e.g., `"john.doe"`)
     */
    principal?: pulumi.Input<string>;
    /**
     * The name of the role to assign
     */
    roleName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RoleAssignment resource.
 */
export interface RoleAssignmentArgs {
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster
     */
    clusterApiUrl: pulumi.Input<string>;
    /**
     * The principal to assign the role to. Specify just the username (e.g., `"john.doe"`)
     */
    principal: pulumi.Input<string>;
    /**
     * The name of the role to assign
     */
    roleName: pulumi.Input<string>;
}
