// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ServerlessCluster extends pulumi.CustomResource {
    /**
     * Get an existing ServerlessCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServerlessClusterState, opts?: pulumi.CustomResourceOptions): ServerlessCluster {
        return new ServerlessCluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'redpanda:index/serverlessCluster:ServerlessCluster';

    /**
     * Returns true if the given object is an instance of ServerlessCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServerlessCluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServerlessCluster.__pulumiType;
    }

    /**
     * The URL of the dataplane API for the serverless cluster
     *
     * @deprecated Deprecated
     */
    declare public /*out*/ readonly clusterApiUrl: pulumi.Output<string>;
    /**
     * Private Console URL for the serverless cluster
     */
    declare public /*out*/ readonly consolePrivateUrl: pulumi.Output<string>;
    /**
     * Public Console URL for the serverless cluster
     */
    declare public /*out*/ readonly consoleUrl: pulumi.Output<string>;
    /**
     * Dataplane API endpoints for the serverless cluster
     */
    declare public /*out*/ readonly dataplaneApi: pulumi.Output<outputs.ServerlessClusterDataplaneApi>;
    /**
     * Kafka API endpoints for the serverless cluster
     */
    declare public /*out*/ readonly kafkaApi: pulumi.Output<outputs.ServerlessClusterKafkaApi>;
    /**
     * Name of the serverless cluster
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Network configuration controlling public/private access to the cluster
     */
    declare public readonly networkingConfig: pulumi.Output<outputs.ServerlessClusterNetworkingConfig>;
    /**
     * Planned deletion information for the serverless cluster.
     */
    declare public /*out*/ readonly plannedDeletion: pulumi.Output<outputs.ServerlessClusterPlannedDeletion>;
    /**
     * Private link ID for the serverless cluster. Must be set if private networking is enabled.
     */
    declare public readonly privateLinkId: pulumi.Output<string>;
    /**
     * Prometheus metrics endpoints for the serverless cluster
     */
    declare public /*out*/ readonly prometheus: pulumi.Output<outputs.ServerlessClusterPrometheus>;
    /**
     * The ID of the Resource Group in which to create the serverless cluster
     */
    declare public readonly resourceGroupId: pulumi.Output<string>;
    /**
     * Schema Registry endpoints for the serverless cluster
     */
    declare public /*out*/ readonly schemaRegistry: pulumi.Output<outputs.ServerlessClusterSchemaRegistry>;
    /**
     * Redpanda specific region of the serverless cluster
     */
    declare public readonly serverlessRegion: pulumi.Output<string>;
    /**
     * Current state of the serverless cluster.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Tags placed on cloud resources.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;

    /**
     * Create a ServerlessCluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerlessClusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServerlessClusterArgs | ServerlessClusterState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServerlessClusterState | undefined;
            resourceInputs["clusterApiUrl"] = state?.clusterApiUrl;
            resourceInputs["consolePrivateUrl"] = state?.consolePrivateUrl;
            resourceInputs["consoleUrl"] = state?.consoleUrl;
            resourceInputs["dataplaneApi"] = state?.dataplaneApi;
            resourceInputs["kafkaApi"] = state?.kafkaApi;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkingConfig"] = state?.networkingConfig;
            resourceInputs["plannedDeletion"] = state?.plannedDeletion;
            resourceInputs["privateLinkId"] = state?.privateLinkId;
            resourceInputs["prometheus"] = state?.prometheus;
            resourceInputs["resourceGroupId"] = state?.resourceGroupId;
            resourceInputs["schemaRegistry"] = state?.schemaRegistry;
            resourceInputs["serverlessRegion"] = state?.serverlessRegion;
            resourceInputs["state"] = state?.state;
            resourceInputs["tags"] = state?.tags;
        } else {
            const args = argsOrState as ServerlessClusterArgs | undefined;
            if (args?.resourceGroupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceGroupId'");
            }
            if (args?.serverlessRegion === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverlessRegion'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["networkingConfig"] = args?.networkingConfig;
            resourceInputs["privateLinkId"] = args?.privateLinkId;
            resourceInputs["resourceGroupId"] = args?.resourceGroupId;
            resourceInputs["serverlessRegion"] = args?.serverlessRegion;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["clusterApiUrl"] = undefined /*out*/;
            resourceInputs["consolePrivateUrl"] = undefined /*out*/;
            resourceInputs["consoleUrl"] = undefined /*out*/;
            resourceInputs["dataplaneApi"] = undefined /*out*/;
            resourceInputs["kafkaApi"] = undefined /*out*/;
            resourceInputs["plannedDeletion"] = undefined /*out*/;
            resourceInputs["prometheus"] = undefined /*out*/;
            resourceInputs["schemaRegistry"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServerlessCluster.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ServerlessCluster resources.
 */
export interface ServerlessClusterState {
    /**
     * The URL of the dataplane API for the serverless cluster
     *
     * @deprecated Deprecated
     */
    clusterApiUrl?: pulumi.Input<string>;
    /**
     * Private Console URL for the serverless cluster
     */
    consolePrivateUrl?: pulumi.Input<string>;
    /**
     * Public Console URL for the serverless cluster
     */
    consoleUrl?: pulumi.Input<string>;
    /**
     * Dataplane API endpoints for the serverless cluster
     */
    dataplaneApi?: pulumi.Input<inputs.ServerlessClusterDataplaneApi>;
    /**
     * Kafka API endpoints for the serverless cluster
     */
    kafkaApi?: pulumi.Input<inputs.ServerlessClusterKafkaApi>;
    /**
     * Name of the serverless cluster
     */
    name?: pulumi.Input<string>;
    /**
     * Network configuration controlling public/private access to the cluster
     */
    networkingConfig?: pulumi.Input<inputs.ServerlessClusterNetworkingConfig>;
    /**
     * Planned deletion information for the serverless cluster.
     */
    plannedDeletion?: pulumi.Input<inputs.ServerlessClusterPlannedDeletion>;
    /**
     * Private link ID for the serverless cluster. Must be set if private networking is enabled.
     */
    privateLinkId?: pulumi.Input<string>;
    /**
     * Prometheus metrics endpoints for the serverless cluster
     */
    prometheus?: pulumi.Input<inputs.ServerlessClusterPrometheus>;
    /**
     * The ID of the Resource Group in which to create the serverless cluster
     */
    resourceGroupId?: pulumi.Input<string>;
    /**
     * Schema Registry endpoints for the serverless cluster
     */
    schemaRegistry?: pulumi.Input<inputs.ServerlessClusterSchemaRegistry>;
    /**
     * Redpanda specific region of the serverless cluster
     */
    serverlessRegion?: pulumi.Input<string>;
    /**
     * Current state of the serverless cluster.
     */
    state?: pulumi.Input<string>;
    /**
     * Tags placed on cloud resources.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}

/**
 * The set of arguments for constructing a ServerlessCluster resource.
 */
export interface ServerlessClusterArgs {
    /**
     * Name of the serverless cluster
     */
    name?: pulumi.Input<string>;
    /**
     * Network configuration controlling public/private access to the cluster
     */
    networkingConfig?: pulumi.Input<inputs.ServerlessClusterNetworkingConfig>;
    /**
     * Private link ID for the serverless cluster. Must be set if private networking is enabled.
     */
    privateLinkId?: pulumi.Input<string>;
    /**
     * The ID of the Resource Group in which to create the serverless cluster
     */
    resourceGroupId: pulumi.Input<string>;
    /**
     * Redpanda specific region of the serverless cluster
     */
    serverlessRegion: pulumi.Input<string>;
    /**
     * Tags placed on cloud resources.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
