// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ServerlessPrivateLink extends pulumi.CustomResource {
    /**
     * Get an existing ServerlessPrivateLink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServerlessPrivateLinkState, opts?: pulumi.CustomResourceOptions): ServerlessPrivateLink {
        return new ServerlessPrivateLink(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'redpanda:index/serverlessPrivateLink:ServerlessPrivateLink';

    /**
     * Returns true if the given object is an instance of ServerlessPrivateLink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServerlessPrivateLink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServerlessPrivateLink.__pulumiType;
    }

    /**
     * Allows deletion of the serverless private link. Defaults to false.
     */
    declare public readonly allowDeletion: pulumi.Output<boolean>;
    /**
     * Cloud provider (aws)
     */
    declare public readonly cloudProvider: pulumi.Output<string>;
    /**
     * Cloud provider specific configuration
     */
    declare public readonly cloudProviderConfig: pulumi.Output<outputs.ServerlessPrivateLinkCloudProviderConfig>;
    /**
     * Timestamp when the serverless private link was created
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Name of the serverless private link
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the Resource Group in which to create the serverless private link
     */
    declare public readonly resourceGroupId: pulumi.Output<string>;
    /**
     * Redpanda serverless region
     */
    declare public readonly serverlessRegion: pulumi.Output<string>;
    /**
     * Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Cloud provider specific status information
     */
    declare public /*out*/ readonly status: pulumi.Output<outputs.ServerlessPrivateLinkStatus>;
    /**
     * Timestamp when the serverless private link was last updated. This value changes on every update operation.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a ServerlessPrivateLink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerlessPrivateLinkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServerlessPrivateLinkArgs | ServerlessPrivateLinkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServerlessPrivateLinkState | undefined;
            resourceInputs["allowDeletion"] = state?.allowDeletion;
            resourceInputs["cloudProvider"] = state?.cloudProvider;
            resourceInputs["cloudProviderConfig"] = state?.cloudProviderConfig;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["name"] = state?.name;
            resourceInputs["resourceGroupId"] = state?.resourceGroupId;
            resourceInputs["serverlessRegion"] = state?.serverlessRegion;
            resourceInputs["state"] = state?.state;
            resourceInputs["status"] = state?.status;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as ServerlessPrivateLinkArgs | undefined;
            if (args?.cloudProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudProvider'");
            }
            if (args?.cloudProviderConfig === undefined && !opts.urn) {
                throw new Error("Missing required property 'cloudProviderConfig'");
            }
            if (args?.resourceGroupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceGroupId'");
            }
            if (args?.serverlessRegion === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverlessRegion'");
            }
            resourceInputs["allowDeletion"] = args?.allowDeletion;
            resourceInputs["cloudProvider"] = args?.cloudProvider;
            resourceInputs["cloudProviderConfig"] = args?.cloudProviderConfig;
            resourceInputs["name"] = args?.name;
            resourceInputs["resourceGroupId"] = args?.resourceGroupId;
            resourceInputs["serverlessRegion"] = args?.serverlessRegion;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["state"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServerlessPrivateLink.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ServerlessPrivateLink resources.
 */
export interface ServerlessPrivateLinkState {
    /**
     * Allows deletion of the serverless private link. Defaults to false.
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * Cloud provider (aws)
     */
    cloudProvider?: pulumi.Input<string>;
    /**
     * Cloud provider specific configuration
     */
    cloudProviderConfig?: pulumi.Input<inputs.ServerlessPrivateLinkCloudProviderConfig>;
    /**
     * Timestamp when the serverless private link was created
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Name of the serverless private link
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the Resource Group in which to create the serverless private link
     */
    resourceGroupId?: pulumi.Input<string>;
    /**
     * Redpanda serverless region
     */
    serverlessRegion?: pulumi.Input<string>;
    /**
     * Current state of the serverless private link (STATE_CREATING, STATE_READY, STATE_DELETING, STATE_FAILED, STATE_UPDATING)
     */
    state?: pulumi.Input<string>;
    /**
     * Cloud provider specific status information
     */
    status?: pulumi.Input<inputs.ServerlessPrivateLinkStatus>;
    /**
     * Timestamp when the serverless private link was last updated. This value changes on every update operation.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ServerlessPrivateLink resource.
 */
export interface ServerlessPrivateLinkArgs {
    /**
     * Allows deletion of the serverless private link. Defaults to false.
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * Cloud provider (aws)
     */
    cloudProvider: pulumi.Input<string>;
    /**
     * Cloud provider specific configuration
     */
    cloudProviderConfig: pulumi.Input<inputs.ServerlessPrivateLinkCloudProviderConfig>;
    /**
     * Name of the serverless private link
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the Resource Group in which to create the serverless private link
     */
    resourceGroupId: pulumi.Input<string>;
    /**
     * Redpanda serverless region
     */
    serverlessRegion: pulumi.Input<string>;
}
