// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Topic extends pulumi.CustomResource {
    /**
     * Get an existing Topic resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TopicState, opts?: pulumi.CustomResourceOptions): Topic {
        return new Topic(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'redpanda:index/topic:Topic';

    /**
     * Returns true if the given object is an instance of Topic.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Topic {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Topic.__pulumiType;
    }

    /**
     * Indicates whether the topic can be deleted.
     */
    declare public readonly allowDeletion: pulumi.Output<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
     */
    declare public readonly clusterApiUrl: pulumi.Output<string>;
    /**
     * A map of string key/value pairs of topic configurations.
     */
    declare public readonly configuration: pulumi.Output<{[key: string]: string}>;
    /**
     * The name of the topic.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The number of partitions for the topic. This determines how the data is distributed across brokers. Increases are fully supported without data loss. Decreases will destroy and recreate the topic if<span pulumi-lang-nodejs=" allowDeletion " pulumi-lang-dotnet=" AllowDeletion " pulumi-lang-go=" allowDeletion " pulumi-lang-python=" allow_deletion " pulumi-lang-yaml=" allowDeletion " pulumi-lang-java=" allowDeletion "> allow_deletion </span>is set to true (defaults to false).
     */
    declare public readonly partitionCount: pulumi.Output<number>;
    /**
     * Manually specify broker ID assignments for partition replicas. If manually assigning replicas, both<span pulumi-lang-nodejs=" replicationFactor " pulumi-lang-dotnet=" ReplicationFactor " pulumi-lang-go=" replicationFactor " pulumi-lang-python=" replication_factor " pulumi-lang-yaml=" replicationFactor " pulumi-lang-java=" replicationFactor "> replication_factor </span>and<span pulumi-lang-nodejs=" partitionCount " pulumi-lang-dotnet=" PartitionCount " pulumi-lang-go=" partitionCount " pulumi-lang-python=" partition_count " pulumi-lang-yaml=" partitionCount " pulumi-lang-java=" partitionCount "> partition_count </span>must be -1. Mutually exclusive with<span pulumi-lang-nodejs=" partitionCount " pulumi-lang-dotnet=" PartitionCount " pulumi-lang-go=" partitionCount " pulumi-lang-python=" partition_count " pulumi-lang-yaml=" partitionCount " pulumi-lang-java=" partitionCount "> partition_count </span>and replication_factor.
     */
    declare public readonly replicaAssignments: pulumi.Output<outputs.TopicReplicaAssignment[] | undefined>;
    /**
     * The replication factor for the topic, which defines how many copies of the data are kept across different brokers for fault tolerance.
     */
    declare public readonly replicationFactor: pulumi.Output<number>;

    /**
     * Create a Topic resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TopicArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TopicArgs | TopicState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TopicState | undefined;
            resourceInputs["allowDeletion"] = state?.allowDeletion;
            resourceInputs["clusterApiUrl"] = state?.clusterApiUrl;
            resourceInputs["configuration"] = state?.configuration;
            resourceInputs["name"] = state?.name;
            resourceInputs["partitionCount"] = state?.partitionCount;
            resourceInputs["replicaAssignments"] = state?.replicaAssignments;
            resourceInputs["replicationFactor"] = state?.replicationFactor;
        } else {
            const args = argsOrState as TopicArgs | undefined;
            if (args?.clusterApiUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'clusterApiUrl'");
            }
            resourceInputs["allowDeletion"] = args?.allowDeletion;
            resourceInputs["clusterApiUrl"] = args?.clusterApiUrl;
            resourceInputs["configuration"] = args?.configuration;
            resourceInputs["name"] = args?.name;
            resourceInputs["partitionCount"] = args?.partitionCount;
            resourceInputs["replicaAssignments"] = args?.replicaAssignments;
            resourceInputs["replicationFactor"] = args?.replicationFactor;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Topic.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Topic resources.
 */
export interface TopicState {
    /**
     * Indicates whether the topic can be deleted.
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
     */
    clusterApiUrl?: pulumi.Input<string>;
    /**
     * A map of string key/value pairs of topic configurations.
     */
    configuration?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the topic.
     */
    name?: pulumi.Input<string>;
    /**
     * The number of partitions for the topic. This determines how the data is distributed across brokers. Increases are fully supported without data loss. Decreases will destroy and recreate the topic if<span pulumi-lang-nodejs=" allowDeletion " pulumi-lang-dotnet=" AllowDeletion " pulumi-lang-go=" allowDeletion " pulumi-lang-python=" allow_deletion " pulumi-lang-yaml=" allowDeletion " pulumi-lang-java=" allowDeletion "> allow_deletion </span>is set to true (defaults to false).
     */
    partitionCount?: pulumi.Input<number>;
    /**
     * Manually specify broker ID assignments for partition replicas. If manually assigning replicas, both<span pulumi-lang-nodejs=" replicationFactor " pulumi-lang-dotnet=" ReplicationFactor " pulumi-lang-go=" replicationFactor " pulumi-lang-python=" replication_factor " pulumi-lang-yaml=" replicationFactor " pulumi-lang-java=" replicationFactor "> replication_factor </span>and<span pulumi-lang-nodejs=" partitionCount " pulumi-lang-dotnet=" PartitionCount " pulumi-lang-go=" partitionCount " pulumi-lang-python=" partition_count " pulumi-lang-yaml=" partitionCount " pulumi-lang-java=" partitionCount "> partition_count </span>must be -1. Mutually exclusive with<span pulumi-lang-nodejs=" partitionCount " pulumi-lang-dotnet=" PartitionCount " pulumi-lang-go=" partitionCount " pulumi-lang-python=" partition_count " pulumi-lang-yaml=" partitionCount " pulumi-lang-java=" partitionCount "> partition_count </span>and replication_factor.
     */
    replicaAssignments?: pulumi.Input<pulumi.Input<inputs.TopicReplicaAssignment>[]>;
    /**
     * The replication factor for the topic, which defines how many copies of the data are kept across different brokers for fault tolerance.
     */
    replicationFactor?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Topic resource.
 */
export interface TopicArgs {
    /**
     * Indicates whether the topic can be deleted.
     */
    allowDeletion?: pulumi.Input<boolean>;
    /**
     * The cluster API URL. Changing this will prevent deletion of the resource on the existing cluster. It is generally a better idea to delete an existing resource and create a new one than to change this value unless you are planning to do state imports
     */
    clusterApiUrl: pulumi.Input<string>;
    /**
     * A map of string key/value pairs of topic configurations.
     */
    configuration?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * The name of the topic.
     */
    name?: pulumi.Input<string>;
    /**
     * The number of partitions for the topic. This determines how the data is distributed across brokers. Increases are fully supported without data loss. Decreases will destroy and recreate the topic if<span pulumi-lang-nodejs=" allowDeletion " pulumi-lang-dotnet=" AllowDeletion " pulumi-lang-go=" allowDeletion " pulumi-lang-python=" allow_deletion " pulumi-lang-yaml=" allowDeletion " pulumi-lang-java=" allowDeletion "> allow_deletion </span>is set to true (defaults to false).
     */
    partitionCount?: pulumi.Input<number>;
    /**
     * Manually specify broker ID assignments for partition replicas. If manually assigning replicas, both<span pulumi-lang-nodejs=" replicationFactor " pulumi-lang-dotnet=" ReplicationFactor " pulumi-lang-go=" replicationFactor " pulumi-lang-python=" replication_factor " pulumi-lang-yaml=" replicationFactor " pulumi-lang-java=" replicationFactor "> replication_factor </span>and<span pulumi-lang-nodejs=" partitionCount " pulumi-lang-dotnet=" PartitionCount " pulumi-lang-go=" partitionCount " pulumi-lang-python=" partition_count " pulumi-lang-yaml=" partitionCount " pulumi-lang-java=" partitionCount "> partition_count </span>must be -1. Mutually exclusive with<span pulumi-lang-nodejs=" partitionCount " pulumi-lang-dotnet=" PartitionCount " pulumi-lang-go=" partitionCount " pulumi-lang-python=" partition_count " pulumi-lang-yaml=" partitionCount " pulumi-lang-java=" partitionCount "> partition_count </span>and replication_factor.
     */
    replicaAssignments?: pulumi.Input<pulumi.Input<inputs.TopicReplicaAssignment>[]>;
    /**
     * The replication factor for the topic, which defines how many copies of the data are kept across different brokers for fault tolerance.
     */
    replicationFactor?: pulumi.Input<number>;
}
