// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getApiKeyId(args?: GetApiKeyIdArgs, opts?: pulumi.InvokeOptions): Promise<GetApiKeyIdResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("clickhouse:index/getApiKeyId:getApiKeyId", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApiKeyId.
 */
export interface GetApiKeyIdArgs {
    name?: string;
}

/**
 * A collection of values returned by getApiKeyId.
 */
export interface GetApiKeyIdResult {
    readonly id: string;
    readonly name: string;
}
export function getApiKeyIdOutput(args?: GetApiKeyIdOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetApiKeyIdResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("clickhouse:index/getApiKeyId:getApiKeyId", {
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApiKeyId.
 */
export interface GetApiKeyIdOutputArgs {
    name?: pulumi.Input<string>;
}
