// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { GetApiKeyIdArgs, GetApiKeyIdResult, GetApiKeyIdOutputArgs } from "./getApiKeyId";
export const getApiKeyId: typeof import("./getApiKeyId").getApiKeyId = null as any;
export const getApiKeyIdOutput: typeof import("./getApiKeyId").getApiKeyIdOutput = null as any;
utilities.lazyLoad(exports, ["getApiKeyId","getApiKeyIdOutput"], () => require("./getApiKeyId"));

export { GetPrivateEndpointConfigArgs, GetPrivateEndpointConfigResult, GetPrivateEndpointConfigOutputArgs } from "./getPrivateEndpointConfig";
export const getPrivateEndpointConfig: typeof import("./getPrivateEndpointConfig").getPrivateEndpointConfig = null as any;
export const getPrivateEndpointConfigOutput: typeof import("./getPrivateEndpointConfig").getPrivateEndpointConfigOutput = null as any;
utilities.lazyLoad(exports, ["getPrivateEndpointConfig","getPrivateEndpointConfigOutput"], () => require("./getPrivateEndpointConfig"));

export { PrivateEndpointRegistrationArgs, PrivateEndpointRegistrationState } from "./privateEndpointRegistration";
export type PrivateEndpointRegistration = import("./privateEndpointRegistration").PrivateEndpointRegistration;
export const PrivateEndpointRegistration: typeof import("./privateEndpointRegistration").PrivateEndpointRegistration = null as any;
utilities.lazyLoad(exports, ["PrivateEndpointRegistration"], () => require("./privateEndpointRegistration"));

export * from "./provider";
import { Provider } from "./provider";

export { ServiceArgs, ServiceState } from "./service";
export type Service = import("./service").Service;
export const Service: typeof import("./service").Service = null as any;
utilities.lazyLoad(exports, ["Service"], () => require("./service"));

export { ServicePrivateEndpointsAttachmentArgs, ServicePrivateEndpointsAttachmentState } from "./servicePrivateEndpointsAttachment";
export type ServicePrivateEndpointsAttachment = import("./servicePrivateEndpointsAttachment").ServicePrivateEndpointsAttachment;
export const ServicePrivateEndpointsAttachment: typeof import("./servicePrivateEndpointsAttachment").ServicePrivateEndpointsAttachment = null as any;
utilities.lazyLoad(exports, ["ServicePrivateEndpointsAttachment"], () => require("./servicePrivateEndpointsAttachment"));

export { ServiceTransparentDataEncryptionKeyAssociationArgs, ServiceTransparentDataEncryptionKeyAssociationState } from "./serviceTransparentDataEncryptionKeyAssociation";
export type ServiceTransparentDataEncryptionKeyAssociation = import("./serviceTransparentDataEncryptionKeyAssociation").ServiceTransparentDataEncryptionKeyAssociation;
export const ServiceTransparentDataEncryptionKeyAssociation: typeof import("./serviceTransparentDataEncryptionKeyAssociation").ServiceTransparentDataEncryptionKeyAssociation = null as any;
utilities.lazyLoad(exports, ["ServiceTransparentDataEncryptionKeyAssociation"], () => require("./serviceTransparentDataEncryptionKeyAssociation"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "clickhouse:index/privateEndpointRegistration:PrivateEndpointRegistration":
                return new PrivateEndpointRegistration(name, <any>undefined, { urn })
            case "clickhouse:index/service:Service":
                return new Service(name, <any>undefined, { urn })
            case "clickhouse:index/servicePrivateEndpointsAttachment:ServicePrivateEndpointsAttachment":
                return new ServicePrivateEndpointsAttachment(name, <any>undefined, { urn })
            case "clickhouse:index/serviceTransparentDataEncryptionKeyAssociation:ServiceTransparentDataEncryptionKeyAssociation":
                return new ServiceTransparentDataEncryptionKeyAssociation(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("clickhouse", "index/privateEndpointRegistration", _module)
pulumi.runtime.registerResourceModule("clickhouse", "index/service", _module)
pulumi.runtime.registerResourceModule("clickhouse", "index/servicePrivateEndpointsAttachment", _module)
pulumi.runtime.registerResourceModule("clickhouse", "index/serviceTransparentDataEncryptionKeyAssociation", _module)
pulumi.runtime.registerResourcePackage("clickhouse", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:clickhouse") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
