// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ServiceTransparentDataEncryptionKeyAssociation extends pulumi.CustomResource {
    /**
     * Get an existing ServiceTransparentDataEncryptionKeyAssociation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceTransparentDataEncryptionKeyAssociationState, opts?: pulumi.CustomResourceOptions): ServiceTransparentDataEncryptionKeyAssociation {
        return new ServiceTransparentDataEncryptionKeyAssociation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'clickhouse:index/serviceTransparentDataEncryptionKeyAssociation:ServiceTransparentDataEncryptionKeyAssociation';

    /**
     * Returns true if the given object is an instance of ServiceTransparentDataEncryptionKeyAssociation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceTransparentDataEncryptionKeyAssociation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceTransparentDataEncryptionKeyAssociation.__pulumiType;
    }

    /**
     * ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
     */
    declare public readonly keyId: pulumi.Output<string>;
    /**
     * ClickHouse Service ID
     */
    declare public readonly serviceId: pulumi.Output<string>;

    /**
     * Create a ServiceTransparentDataEncryptionKeyAssociation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceTransparentDataEncryptionKeyAssociationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceTransparentDataEncryptionKeyAssociationArgs | ServiceTransparentDataEncryptionKeyAssociationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceTransparentDataEncryptionKeyAssociationState | undefined;
            resourceInputs["keyId"] = state?.keyId;
            resourceInputs["serviceId"] = state?.serviceId;
        } else {
            const args = argsOrState as ServiceTransparentDataEncryptionKeyAssociationArgs | undefined;
            if (args?.keyId === undefined && !opts.urn) {
                throw new Error("Missing required property 'keyId'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            resourceInputs["keyId"] = args?.keyId;
            resourceInputs["serviceId"] = args?.serviceId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceTransparentDataEncryptionKeyAssociation.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ServiceTransparentDataEncryptionKeyAssociation resources.
 */
export interface ServiceTransparentDataEncryptionKeyAssociationState {
    /**
     * ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
     */
    keyId?: pulumi.Input<string>;
    /**
     * ClickHouse Service ID
     */
    serviceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ServiceTransparentDataEncryptionKeyAssociation resource.
 */
export interface ServiceTransparentDataEncryptionKeyAssociationArgs {
    /**
     * ID of the Encryption key to use for data encryption. Must be an ARN for AWS services or a Key Resource Path for GCP services.
     */
    keyId: pulumi.Input<string>;
    /**
     * ClickHouse Service ID
     */
    serviceId: pulumi.Input<string>;
}
