// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ServiceBackupConfiguration {
    /**
     * Interval in hours between each backup.
     */
    backupPeriodInHours: number;
    /**
     * How long in hours to keep a backup before deleting it.
     */
    backupRetentionPeriodInHours: number;
    /**
     * Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set,<span pulumi-lang-nodejs=" backupPeriodInHours " pulumi-lang-dotnet=" BackupPeriodInHours " pulumi-lang-go=" backupPeriodInHours " pulumi-lang-python=" backup_period_in_hours " pulumi-lang-yaml=" backupPeriodInHours " pulumi-lang-java=" backupPeriodInHours "> backup_period_in_hours </span>must be null and backups are created once a day.
     */
    backupStartTime?: string;
}

export interface ServiceEndpoints {
    https: outputs.ServiceEndpointsHttps;
    mysql?: outputs.ServiceEndpointsMysql;
    nativesecure: outputs.ServiceEndpointsNativesecure;
}

export interface ServiceEndpointsHttps {
    /**
     * Endpoint host.
     */
    host: string;
    /**
     * Endpoint port.
     */
    port: number;
}

export interface ServiceEndpointsMysql {
    /**
     * Wether to enable the mysql endpoint or not.
     */
    enabled: boolean;
    /**
     * Endpoint host.
     */
    host: string;
    /**
     * Endpoint port.
     */
    port: number;
}

export interface ServiceEndpointsNativesecure {
    /**
     * Endpoint host.
     */
    host: string;
    /**
     * Endpoint port.
     */
    port: number;
}

export interface ServiceIpAccess {
    /**
     * Description of the IP address.
     */
    description: string;
    /**
     * IP address allowed to access the service. In case you want to set the<span pulumi-lang-nodejs=" ipAccess " pulumi-lang-dotnet=" IpAccess " pulumi-lang-go=" ipAccess " pulumi-lang-python=" ip_access " pulumi-lang-yaml=" ipAccess " pulumi-lang-java=" ipAccess "> ip_access </span>to anywhere you should set source to 0.0.0.0/0
     */
    source: string;
}

export interface ServicePrivateEndpointConfig {
    /**
     * Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
     */
    endpointServiceId: string;
    /**
     * Private DNS Hostname of the VPC you created.
     */
    privateDnsHostname: string;
}

export interface ServiceQueryApiEndpoints {
    /**
     * Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
     */
    allowedOrigins?: string;
    /**
     * The UUIDs of the API Keys to grant access to the query API.
     */
    apiKeyIds: string[];
    /**
     * The Database role that will be used to run the query.
     */
    roles: string[];
}

export interface ServiceTransparentDataEncryption {
    /**
     * If true, TDE is enabled for the service.
     */
    enabled: boolean;
    /**
     * ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
     */
    roleId: string;
}

