// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("clickhouse");

/**
 * API URL of the ClickHouse OpenAPI the provider will interact with. Alternatively, can be configured using the `CLICKHOUSE_API_URL` environment variable. Only specify if you have a specific deployment of the ClickHouse OpenAPI you want to run against.
 */
export declare const apiUrl: string | undefined;
Object.defineProperty(exports, "apiUrl", {
    get() {
        return __config.get("apiUrl");
    },
    enumerable: true,
});

/**
 * ID of the organization the provider will create services under. Alternatively, can be configured using the `CLICKHOUSE_ORG_ID` environment variable.
 */
export declare const organizationId: string | undefined;
Object.defineProperty(exports, "organizationId", {
    get() {
        return __config.get("organizationId");
    },
    enumerable: true,
});

/**
 * Timeout in seconds for the HTTP client.
 */
export declare const timeoutSeconds: number | undefined;
Object.defineProperty(exports, "timeoutSeconds", {
    get() {
        return __config.getObject<number>("timeoutSeconds");
    },
    enumerable: true,
});

/**
 * Token key of the key/secret pair. Used to authenticate with OpenAPI. Alternatively, can be configured using the `CLICKHOUSE_TOKEN_KEY` environment variable.
 */
export declare const tokenKey: string | undefined;
Object.defineProperty(exports, "tokenKey", {
    get() {
        return __config.get("tokenKey");
    },
    enumerable: true,
});

/**
 * Token secret of the key/secret pair. Used to authenticate with OpenAPI. Alternatively, can be configured using the `CLICKHOUSE_TOKEN_SECRET` environment variable.
 */
export declare const tokenSecret: string | undefined;
Object.defineProperty(exports, "tokenSecret", {
    get() {
        return __config.get("tokenSecret");
    },
    enumerable: true,
});

