name: es-node

on:
  pull_request:
    paths:
      - 'es-node/**'

defaults:
  run:
    working-directory: ./es-node

jobs:
  es-node:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - run: pnpm type:check
