name: Jex

on:
  pull_request:
    paths:
      - 'jex/**'

defaults:
  run:
    working-directory: ./jex

jobs:
  jex:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
      - name: Install And Build
        run: pnpm install && pnpm build
      - name: Format Check
        run: pnpm format:check
      - name: Type Check
        run: pnpm type:check
      - name: Test
        run: pnpm test
