name: Log4Bot

on:
  pull_request:
    paths:
      - 'log4bot/**'

defaults:
  run:
    working-directory: ./log4bot

jobs:
  log4bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Install And Build
        run: yarn install && yarn build
      - name: Test
        run: yarn test
