name: Opapi

on:
  push:
    branches:
      - master

  pull_request:
    paths:
      - 'opapi/**'

  workflow_dispatch: {}

defaults:
  run:
    working-directory: ./opapi

jobs:
  opapi:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 9.1.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm type:check
      - run: pnpm format:check
      - run: pnpm test
      - name: Publish
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        uses: botpress/gh-actions/publish-if-not-exists@master
        with:
          path: './opapi'
          token: '${{ secrets.NPM_ACCESS_TOKEN }}'
