name: Zui

on:
  pull_request:
    paths:
      - 'zui/**'

defaults:
  run:
    working-directory: ./zui

jobs:
  zui:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - name: Type Check
        run: pnpm type:check
      - name: Install And Build
        run: pnpm install && pnpm build
      - name: Format Check
        run: pnpm format:check
      - name: Test
        run: pnpm test
