name: Zui

on:
  pull_request:
    paths:
      - 'zui/**'

defaults:
  run:
    working-directory: ./zui

jobs:
  zui:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true
          cache: 'pnpm'
      - name: Install And Build
        run: pnpm install
      - name: Type Check
        run: pnpm type:check
      - name: Build
        run: pnpm build
      - name: Format Check
        run: pnpm format:check
      - name: Test
        run: pnpm test
